<?php use function App\Core\{e,url,csrf_field}; ?>
<section class="card"><h1>API投稿</h1><p>FANZA・DUGA・SOKMILから商品情報・サンプル画像・サンプル動画を取得して投稿素材を作ります。</p></section>
<section class="grid">
<?php $serviceFields=['fanza'=>['FANZA',['api_id'=>'API ID','affiliate_id'=>'アフィリエイトID']],'duga'=>['DUGA',['appid'=>'APP ID','agentid'=>'AGENT ID']],'sokmil'=>['SOKMIL',['affiliate_id'=>'アフィリエイトID','endpoint'=>'APIエンドポイント']]]; ?>
<?php foreach($serviceFields as $service=>$definition): ?><article class="card"><h2><?= e($definition[0]) ?> API設定</h2><form method="post" action="<?= e(url('/products/api')) ?>"><?= csrf_field() ?><input type="hidden" name="service" value="<?= e($service) ?>"><?php foreach($definition[1] as $field=>$label): ?><label><?= e($label) ?><input name="credentials[<?= e($field) ?>]" value="<?= e($apiSettings[$service][$field]??'') ?>" autocomplete="off"></label><?php endforeach; ?><button class="primary">API設定を保存</button></form></article><?php endforeach; ?>
</section>
<section class="card"><h2>商品を一括取得</h2><form method="post" action="<?= e(url('/products/search')) ?>"><?= csrf_field() ?><p><label><input type="checkbox" name="services[]" value="fanza" checked> FANZA</label>　<label><input type="checkbox" name="services[]" value="duga" checked> DUGA</label>　<label><input type="checkbox" name="services[]" value="sokmil" checked> SOKMIL</label></p><label>キーワード<input name="keyword" placeholder="空欄なら新着、または女優名・ジャンル・作品名"></label><button class="primary">選択したAPIから一括取得</button></form></section>
<?php if($results): ?><section class="card"><h2>取得結果</h2><form method="post" action="<?= e(url('/products/save')) ?>"><?= csrf_field() ?><p><label><input type="checkbox" data-result-all> 全選択</label> <button class="primary">選択した商品を投稿候補へ一括保存</button></p><div class="cards"><?php foreach($results as $index=>$product): ?><article><label><input type="checkbox" name="indexes[]" value="<?= (int)$index ?>" data-result-check> 選択</label><?php if(!empty($product['image_url'])):?><img src="<?= e($product['image_url']) ?>" alt="" loading="lazy"><?php endif; ?><h3><?= e($product['title']??'') ?></h3><p><strong>サービス：</strong><?= e(strtoupper((string)($product['service']??''))) ?></p><?php if(!empty($product['actress'])):?><p><strong>出演者：</strong><?= e($product['actress']) ?></p><?php endif; ?><button class="primary" name="index" value="<?= (int)$index ?>">この商品だけ保存</button></article><?php endforeach; ?></div></form></section><?php endif; ?>
<section class="card"><h2>保存済みの商品</h2><?php if(!$products):?><p>保存済みの商品はありません。</p><?php else:?><form method="post" action="<?= e(url('/products/delete')) ?>" onsubmit="return confirm('選択した商品を削除しますか？')"><?= csrf_field() ?><p><label><input type="checkbox" data-product-all> 全選択</label> <button>選択した商品を一括削除</button></p><div class="table-wrap"><table><thead><tr><th></th><th>サービス</th><th>タイトル</th><th>出演者</th><th>操作</th></tr></thead><tbody><?php foreach($products as $product):?><tr><td><input type="checkbox" name="ids[]" value="<?= (int)$product['id'] ?>" data-product-check></td><td><?= e(strtoupper((string)$product['service'])) ?></td><td><?= e($product['title']) ?></td><td><?= e($product['actress']??'') ?></td><td><button name="id" value="<?= (int)$product['id'] ?>" onclick="return confirm('この商品を削除しますか？')">個別削除</button></td></tr><?php endforeach;?></tbody></table></div></form><?php endif;?></section>
<script>
const ra=document.querySelector('[data-result-all]');if(ra)ra.addEventListener('change',()=>document.querySelectorAll('[data-result-check]').forEach(c=>c.checked=ra.checked));
const pa=document.querySelector('[data-product-all]');if(pa)pa.addEventListener('change',()=>document.querySelectorAll('[data-product-check]').forEach(c=>c.checked=pa.checked));
</script>